apiVersion : apps/v1
kind: Deployment
metadata:
  name: samplesnginxakswithacr12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
        - name: sampleapp
          image: registrynew12.azurecr.io/my-app:v1
          ports:
          - containerPort: 80


